#!/bin/bash
# This funtion return the sum of the array
function sumArray {
	local myarray=($(echo "$@"))
	local sum=0
	for value in ${myarray[*]}
	do
		sum=$[ $sum + $value ]
	done
	echo $sum
}
myarray=(1 2 3 4 5)
echo "The original array is ${myarray[*]}"
arg1=${myarray[*]}
result=$(sumArray $arg1)
echo "The result is $result"
