#!/bin/bash
# format of defining a function in script
# function name {
# 		 commands
#}

function funct1 {
	echo "This is example of function"
	ls
}
function double {
		read -p "Enter Value: " value
		echo $[ $value * 2 ]
}
#funct1
result=$(double)
echo "The double value is $result"

