#!/bin/bash
#Passing script parameter inside a function

function mult {
	echo $[ $1 * $2 ]
}

if [ $# -eq 2 ]
then
	value=$(mult $1 $2)
	echo "The result of value is $value"
else
	echo "Usage: filename a b"
fi

