#!/bin/bash

location=/home/hemant/MyDrive/movies
echo "Iterate through directory $location and checking it"
var=0
var1=0
for file in $location/*
do
	echo
	if [ -d "$file" ]
	then
		echo "$file is directory!"
		(( var = $var + 1 ))
	elif [ -f "$file" ]
	then
		echo "$file is file!"
		(( var1 =  $var1 + 1 ))
	fi
done

echo "$var is no. of directory"
echo "$var1 is no. of files"

echo
echo "Iterating through multiple files"
echo
for file in /home/hemant/.b* /home/hemant/badtest
do
if [ -d "$file" ]
then
echo "$file is a directory"
elif [ -f "$file" ]
then
echo "$file is a file"
else
echo "$file doesn't exist"
fi
done
