#!/bin/bash

#Checking for reading of a file
file_name=/etc/shadow
echo "Checking status for file $file_name"
if [ -f $file_name ]
then
	echo "File exists"
	echo "Checking Reading status of file"
	if [ -r $file_name ]
	then
		tail $file_name
	else
		echo "$file_name file is unreadable"
	fi
else
	echo "File does not exists"
fi
