#!/bin/bash

echo "This assign 3 file desc to 1 file desc"

exec 3>&1
exec 1> redDescOut
echo "This is in file"
echo "This is infile"
exec 1>&3 
echo "This is on terminal"

# exec 3>> testfile can be use define file descriptor to append in file
